spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Mook@2736
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    
    oracle:
#        driver-class-name: oracle.jdbc.driver.OracleDriver
        jdbc-url: jdbc:oracle:thin:@localhost:1521/ORCL
        username: system
        password: Mook@2736


server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:mapper/*.xml